"""python3 run_react_booktabs.py - the Books tabs other than TDS and GST in React, with the books in tests/data: Tally
ledgers (a meaning set, confirmed and undone, the find box, confirm the shown, the posting ledgers), and more as they
move. Run on the React build: TDSDESK_SITE=../app/dist-test python3 run_react_booktabs.py"""
import json, os, threading, functools, http.server
FCY = lambda y: y + '-' + str(int(y) + 1)[2:]
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers")
from playwright.sync_api import sync_playwright
H = functools.partial(http.server.SimpleHTTPRequestHandler, directory=os.environ.get("TDSDESK_SITE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "dist-test"))); H.log_message = lambda *a: None
srv = http.server.ThreadingHTTPServer(("localhost", 8158), H); threading.Thread(target=srv.serve_forever, daemon=True).start()
books = json.load(open(os.environ.get("TDSDESK_CACHE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "books-cache.json"))))
fails, errors = [], []
def ok(c, w):
    print(("  ok   " if c else "  FAIL ") + w)
    if not c: fails.append(w)
with sync_playwright() as p:
    br = p.chromium.launch(); pg = br.new_page(viewport={"width": 1400, "height": 1000}); pg.on("pageerror", lambda e: errors.append(str(e)))
    pg.goto("http://localhost:8158/"); pg.wait_for_timeout(2500); pg.click('button[data-act="useOffline"]'); pg.wait_for_timeout(1500)
    pg.evaluate("""(bk) => { const c = newCompany({name: "ZZ TEST", gstin: "09AANFG3202D1ZR"}); S.companies[c.id] = c; S.coId = c.id; S.view = "company"; S.tab = "books"; S.loadingCo = false;
      S.books = Object.assign({loading: false, challans: [], alloc: {}}, bk, {cid: c.id}); S.books.map = Books.mapLedgers(bk.vouchers, {}); LedMaster.refresh(S.books); window.__bk = S.books; S.booksTab = "ledgers"; render(); }""", books)
    pg.wait_for_timeout(1200); pg.evaluate("S.books = window.__bk; render();"); pg.wait_for_timeout(600)
    # Tally ledgers
    pend = lambda: pg.evaluate("LedMaster.pending(S.books).length")
    n0 = pend()
    # FinCom 2.4.0, the simpler page: each ledger to confirm on one row (GST ledgers, TDS ledgers, or Needs you)
    keys = lambda: pg.evaluate("() => [...document.querySelectorAll('#app [data-led-table] tr[data-key]')].map(r => r.dataset.key)")
    pn = pg.evaluate("LedMaster.pending(S.books).map(([n]) => n)")
    ok(n0 > 0 and all(k in keys() for k in pn), "Tally ledgers: the %d to confirm are listed" % n0)
    row = pg.locator("#app [data-led-table] tbody tr:has([data-led-confirm])").first; name = row.get_attribute("data-key")
    row.locator("[data-led-confirm]").click(); pg.wait_for_timeout(400)
    ok(pend() == n0 - 1 and pg.evaluate("S.books.map[%s].ok" % json.dumps(name)), "Confirm: %s confirmed, one fewer to confirm" % name)
    pg.click("#app [data-led-show-done]"); pg.wait_for_timeout(400)
    pg.locator('#app tr[data-key=%s] [data-led-undo]' % json.dumps(name)).click(); pg.wait_for_timeout(400)
    ok(pend() == n0 and not pg.evaluate("S.books.map[%s].ok" % json.dumps(name)), "✓ Confirmed, clicked: undone")
    pg.click("#app [data-led-show-done]"); pg.wait_for_timeout(300)
    pg.click("#app [data-more-toggle=ledpage]"); pg.wait_for_timeout(300)
    pg.click('nav[aria-label="Ledgers"] button:has-text("Other ledgers")'); pg.wait_for_timeout(400)
    other = pg.locator("#lmTable tbody tr").first.get_attribute("data-key")
    box = pg.locator('input[aria-label="Find a ledger"]'); box.click(); pg.keyboard.type(other[:8], delay=15); pg.wait_for_timeout(600)
    ok(pg.evaluate("document.activeElement.getAttribute('aria-label')") == "Find a ledger" and pg.locator("#lmTable tbody tr").count() >= 1, "the find box filters as typed, keeping the cursor")
    pg.select_option('select[aria-label="What %s is"]' % other, "tds_payable"); pg.wait_for_timeout(500)
    m = pg.evaluate("S.books.map[%s]" % json.dumps(other))
    ok(m["what"] == "tds_payable" and m["ok"], "an other ledger made a TDS ledger: kept, and confirmed as the user's own choice")
    # now a confirmed TDS ledger: shown with the confirmed, changed there
    pg.evaluate("lmViewGo('done')"); pg.wait_for_timeout(400)
    pg.click('#app [data-led-table=tds] tr[data-key=%s] [data-led-change]' % json.dumps(other)); pg.wait_for_timeout(300)
    sec = pg.locator('input[aria-label="Section of %s"]' % other); sec.fill("194j"); sec.press("Tab"); pg.wait_for_timeout(400)
    ok(pg.evaluate("S.books.map[%s].section" % json.dumps(other)) == "194J", "its section typed, kept in capitals")
    # review 18 (02-Oct-2026): what is chosen or typed on the page is saved with Save at its foot; Confirm buttons save at once
    ok("Not saved yet" in pg.inner_text('#app [data-confirm-foot="books:ledgers"]'), "review 18: the ledger's kind and section are not saved until Save")
    pg.click('#app [data-confirm-foot="books:ledgers"] [data-cfm="save"]'); pg.wait_for_timeout(400)
    box.fill(""); pg.evaluate("S.ledEdit = ''; lmViewGo('pending')"); pg.wait_for_timeout(400)
    for sec_ in ("gst", "tds"):
        if pg.locator("#app [data-led-confirm-all=%s]" % sec_).count(): pg.click("#app [data-led-confirm-all=%s]" % sec_); pg.wait_for_timeout(500)
    while pg.locator("#app [data-led-table] tbody tr [data-led-confirm]").count():
        pg.locator("#app [data-led-table] tbody tr [data-led-confirm]").first.click(); pg.wait_for_timeout(300)
    # a ledger FinCom could not tell is chosen by hand (Needs you), then confirmed
    for k in pg.evaluate("LedMaster.pending(S.books).map(([n]) => n)"):
        pg.evaluate("(n) => lmSet(n, 'what', 'none')", k); pg.wait_for_timeout(100)
    ok(pend() == 0 and "No GST ledger to confirm." in pg.inner_text("#app"), "Confirm all: nothing left to confirm")
    pg.click("#app [data-more-toggle=ledpage]") if pg.locator('nav[aria-label="Ledgers"]').count() == 0 else None; pg.wait_for_timeout(300)
    pg.click('nav[aria-label="Ledgers"] button:has-text("What FinCom posts to")'); pg.wait_for_timeout(400)
    ok("What FinCom posts bills to" in pg.inner_text("#app"), "What FinCom posts to: the posting ledgers")
    # Audit: run, open a finding, its status and note, an area, related parties, the 3CD draft
    pg.evaluate("() => { S.booksTab = 'audit'; S.books.stale = {}; render(); }"); pg.wait_for_timeout(500)
    pg.fill('input[aria-label="Audit from"]', "2025-04-01"); pg.fill('input[aria-label="Audit to"]', "2026-03-31")
    pg.click('button:text-is("Run now")'); pg.wait_for_timeout(3000)
    run = pg.evaluate("S.books.audit && S.books.audit.last && {n: S.books.audit.last.findings.length, from: S.books.audit.last.from}")
    ok(run and run["n"] > 0 and run["from"] == "20250401", "Run now: findings for the period chosen (%s)" % run)
    fid = pg.evaluate("S.books.audit.last.findings[0].id")
    sec = 'section[data-key=%s]' % json.dumps(fid)
    pg.click(sec + ' > .row button.linkbtn'); pg.wait_for_timeout(400)
    ok("Effect." in pg.inner_text(sec), "a finding opens: its effect and what to do")
    pg.select_option(sec + ' > .row select', "pass"); pg.wait_for_timeout(400)
    note = pg.locator(sec + ' input[aria-label="Note for the report"]'); note.fill("to reverse"); note.press("Tab"); pg.wait_for_timeout(400)
    st = pg.evaluate("S.books.audit.st[%s]" % json.dumps(fid))
    ok(st["s"] == "pass" and st["note"] == "to reverse", "its status and note are kept")
    pg.evaluate("document.querySelectorAll('#app details').forEach(d => d.open = true)")   # settings sit in a closed section
    pg.select_option('select[aria-label="Run on its own"]', "weekly"); pg.wait_for_timeout(300)
    ok(pg.evaluate("Audit.cfg(S.books).freq") == "weekly", "how often it runs by itself is kept")
    pg.click('#app [data-confirm-foot="books:audit-settings"] [data-cfm="save"]'); pg.wait_for_timeout(300)   # review 18: saved with Save
    pg.click('nav[aria-label="Audit"] button:text-is("Related parties")'); pg.wait_for_timeout(400)
    led = pg.evaluate("Object.keys(S.books.map).sort()[0]")
    pg.fill("#relq", led); pg.click('.row:has(#relq) button:text-is("Add")'); pg.wait_for_timeout(400)
    pg.select_option('select[aria-label="Relation of %s"]' % led, "Director"); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.books.auditRel") == [{"name": led, "relation": "Director"}], "a related party added from the list, with its relation")
    pg.click('tr[data-key=%s] button:text-is("remove")' % json.dumps(led)); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.books.auditRel.length") == 0, "and removed")
    pg.click('nav[aria-label="Audit"] button:text-is("Form 3CD draft")'); pg.wait_for_timeout(600)
    ok(pg.locator(".audit3cd table").count() > 0, "the Form 3CD draft, filled from the run")
    # MIS: a quick period, run now, the tabs, a party opened and filtered, a supplier marked MSME, a budget month, how often
    pg.evaluate("() => { S.booksTab = 'mis'; S.books.mis = null; S.misRange = null; S.books.stale = {}; render(); }"); pg.wait_for_timeout(500)
    pg.click('button:text-is("Last year")'); pg.wait_for_timeout(300)
    rg = pg.evaluate("S.misRange"); ok(pg.input_value('input[aria-label="MIS from"]') == rg["from"], "a quick period fills the dates (%s)" % rg)
    pg.fill('input[aria-label="MIS from"]', "2025-04-01"); pg.fill('input[aria-label="MIS to"]', "2025-06-30"); pg.wait_for_timeout(200)
    pg.click('section[data-mis-head] button:text-is("Run now")'); pg.wait_for_timeout(3000)
    r = pg.evaluate("S.books.mis && S.books.mis.last && {from: S.books.mis.last.from, to: S.books.mis.last.to}")
    ok(r == {"from": "20250401", "to": "20250630"}, "Run now: the MIS for the dates typed (%s)" % r)
    ok("Sales, the period" in pg.inner_text("#app"), "the summary")
    pg.click('nav[aria-label="MIS"] button:text-is("Receivables")'); pg.wait_for_timeout(400)
    party = pg.locator("#misAge tbody tr[data-key]").first.get_attribute("data-key")
    pg.click('#misAge tr[data-key=%s] button.linkbtn' % json.dumps(party)); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.misOpen") == party and pg.locator("#misAge th:text-is('Left after amounts on account')").count() == 1, "a customer opens to its bills")
    pg.fill("#misq", party[:5]); pg.wait_for_timeout(600)
    ok(all(party[:5].lower() in (x or "").lower() for x in pg.locator("#misAge tbody tr[data-key]").evaluate_all("rs => rs.map(r => r.dataset.key)")), "the search keeps only matching customers")
    ok(pg.evaluate("document.activeElement.id") == "misq", "the search box keeps the cursor")
    pg.click('nav[aria-label="MIS"] button:text-is("Payables")'); pg.wait_for_timeout(400)
    ok(pg.input_value("#misq") == "", "a new tab starts with no search")
    sel = pg.locator('select[aria-label^="MSME: "]').first; sup = sel.get_attribute("aria-label")[6:]
    sel.select_option("Micro"); pg.wait_for_timeout(1500)
    ok(pg.evaluate("S.books.msme[%s]" % json.dumps(sup)) == "Micro", "a supplier marked micro is kept")
    pg.select_option('select[aria-label="Which parties"]', "msme"); pg.wait_for_timeout(400)
    ok(pg.locator("#misAge tbody tr[data-key]").count() >= 1, "and shows under MSME suppliers")
    pg.click('nav[aria-label="MIS"] button:text-is("Profit and loss")'); pg.wait_for_timeout(400)
    hk = pg.evaluate("(() => { const h = S.books.mis.last.pl.heads; return ['exp', ...Object.keys(h)].find(k => h[k] && h[k].led.length > 1); })()")
    n = pg.evaluate("S.books.mis.last.pl.heads[%s].led.length" % json.dumps(hk))
    pg.click('#misPl button:text-is("\u25b8 %d ledgers")' % n); pg.wait_for_timeout(300)
    led = pg.evaluate("S.books.mis.last.pl.heads[%s].led[0].l" % json.dumps(hk))
    pg.locator("#misPl button.linkbtn").filter(has_text=led).first.click(); pg.wait_for_timeout(400)
    ok(pg.locator("h3").filter(has_text=led).count() == 1, "a ledger's entries open from the profit and loss")
    pg.click('nav[aria-label="MIS"] button:text-is("Cash flow")'); pg.wait_for_timeout(400)
    pg.click("#misFc tbody tr:first-child button.linkbtn"); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.misWeek") == 0 and pg.locator("#misFc th:text-is('Why this date')").count() == 1, "a week of the forecast opens")
    pg.click('nav[aria-label="MIS"] button:text-is("Budget")'); pg.wait_for_timeout(400)
    box = pg.locator('input[aria-label="Budget Revenue from operations Apr-2025"]')
    box.fill("250000"); box.press("Tab"); pg.wait_for_timeout(500)
    ok(pg.evaluate("S.books.budget['2025'].rev['202504']") == 250000, "a budget month is kept")
    ok("2,50,000.00" in pg.inner_text("#app"), "and the year's total follows")
    pg.evaluate("document.querySelectorAll('#app details').forEach(d => d.open = true)")
    pg.select_option('select[aria-label="MIS runs on its own"]', "weekly"); pg.wait_for_timeout(300)
    ok(pg.evaluate("MIS.cfg(S.books).freq") == "weekly", "how often the MIS runs by itself is kept")
    pg.click('#app [data-confirm-foot="books:mis-settings"] [data-cfm="save"]'); pg.wait_for_timeout(300)   # review 18: saved with Save
    # Reports: charts, the year, finding a report, a figure and a report opening their screens
    pg.evaluate("() => { S.booksTab = 'reports'; S.rptQ = ''; render(); }"); pg.wait_for_timeout(800)
    ok(pg.locator(".rpt-area .fc-chart svg rect").count() > 20 and pg.locator(".rpt-link").count() >= 30, "every area with its chart, every report listed")
    ys = pg.evaluate("RPT.fys()"); y = ys[1] if len(ys) > 1 else ys[0]   # the client's books may hold one year only
    pg.select_option('select[aria-label="Year"]', y); pg.wait_for_timeout(600)
    ok(pg.evaluate("RPT.range().fy") == y and FCY(y) in pg.inner_text(".rpt-overview .rpt-ah"), "another year")
    pg.fill("#rptQ", "ageing"); pg.wait_for_timeout(600)
    ok(pg.locator(".rpt-link").count() == 2 and pg.evaluate("document.activeElement.id") == "rptQ", "finding a report by name, keeping the cursor")
    pg.click('.rpt-link:has(b:text-is("Receivables ageing"))'); pg.wait_for_timeout(1500)
    ok(pg.evaluate("[S.booksTab, S.misTab, !!(S.books.mis && S.books.mis.last)]") == ["mis", "recv", True], "a report opens its screen, worked out")
    pg.evaluate("() => { S.booksTab = 'reports'; S.rptQ = ''; render(); }"); pg.wait_for_timeout(600)
    pg.click('.rpt-gst button.dtile:has(span:text-is("Input credit"))'); pg.wait_for_timeout(800)
    ok(pg.evaluate("[S.booksTab, S.gstPart]") == ["gst", "inreg"], "a figure opens its report")
    # Look up: a question in plain words (Enter), an entry opened and a ledger in it, each kind, a preset, the month, recent
    # the balances, as brought in from a trial balance (the books here have none of their own)
    pg.evaluate("() => { const led = {}; Object.keys(S.books.map).forEach(n => { led[n] = {open: 0, close: 0}; }); S.books.tb = {from: '20250401', to: '20270331', at: '2026-01-01T00:00:00Z', led}; S.booksTab = 'lookup'; S.lk = null; render(); }"); pg.wait_for_timeout(500)
    pg.fill("#lkAsk", "HDFC bank for June 2025"); pg.keyboard.press("Enter"); pg.wait_for_timeout(1200)
    r = pg.evaluate("({kind: S.lk.kind, led: S.lk.led, from: S.lk.from, to: S.lk.to, rows: S.lk.res && S.lk.res.rows.length})")
    ok(r["kind"] == "ledger" and r["led"] == "HDFC BANK" and r["from"] == "20250601" and r["to"] == "20250630" and r["rows"] > 0, "a question in plain words: " + json.dumps(r))
    ok("Understood as:" in pg.inner_text(".lk-ask"), "and what was understood")
    pg.locator("tr.lk-v").first.click(); pg.wait_for_timeout(400)
    ok(pg.locator("tr.lk-sub .lk-in tr").count() >= 2, "an entry opens to both sides")
    other = [t for t in pg.locator("tr.lk-sub button.linkbtn").all_inner_texts() if t != "HDFC BANK"][0]
    pg.locator("tr.lk-sub button.linkbtn", has_text=other).first.click(); pg.wait_for_timeout(1000)
    ok(pg.evaluate("[S.lk.led, S.lk.res.led]") == [other, other], "a ledger in it opens its account: " + other)
    pg.click('.lk-kinds button:text-is("Group summary")'); pg.wait_for_timeout(300)
    g = pg.locator('input[aria-label="Group"]'); g.fill("Sundry Debtors"); pg.wait_for_timeout(200)
    ok(pg.evaluate("document.activeElement.getAttribute('aria-label')") == "Group", "typing keeps the cursor")
    pg.click('.lk-presets button:text-is("Last year")'); pg.wait_for_timeout(1200)
    ok(pg.evaluate("S.lk.res && S.lk.res.kind") == "group" and pg.evaluate("S.lk.grp") == "Sundry Debtors", "a group for a preset period")
    pg.click('.lk-kinds button:text-is("Month by month")'); pg.fill('input[aria-label="Ledger (or leave empty and choose a group)"]', "HDFC BANK"); pg.fill('input[aria-label="Group"]', "")
    pg.fill('input[aria-label="From"]', "2025-04-01"); pg.fill('input[aria-label="To"]', "2026-03-31"); pg.click('button:text-is("Show")'); pg.wait_for_timeout(1200)
    ok(pg.evaluate("S.lk.res.kind") == "monthly" and pg.locator(".lk-res .fc-chart rect").count() > 0, "month by month, with its chart")
    pg.locator(".lk-res tbody button.linkbtn").first.click(); pg.wait_for_timeout(1200)
    ok(pg.evaluate("[S.lk.kind, S.lk.from.slice(6)]") == ["ledger", "01"], "a month opens that month's account")
    pg.click('.lk-kinds button:text-is("Trial balance on a date")'); pg.fill('input[aria-label="As on"]', "2026-06-30"); pg.keyboard.press("Enter"); pg.wait_for_timeout(1200)
    ok(pg.evaluate("S.lk.res.kind") == "tb" and "Debit balances" in pg.inner_text(".lk-res"), "the trial balance on a date (Enter)")
    pg.click('.lk-kinds button:text-is("Find entries")'); pg.fill('input[aria-label="Words, a number or an amount"]', "hdfc"); pg.click('button:text-is("Show")'); pg.wait_for_timeout(1200)
    ok(pg.evaluate("S.lk.res.kind") == "find" and pg.evaluate("S.lk.res.rows.length") > 0, "finding entries")
    pg.evaluate("() => { window.__saved = []; window.saveFile = (n) => window.__saved.push(n); }")
    pg.click('.lk-res button:text-is("Excel")'); pg.wait_for_timeout(2500)
    ok(len(pg.evaluate("window.__saved")) == 1, "the answer as Excel")
    pg.click('.lk-res button:text-is("Close")'); pg.wait_for_timeout(300)
    ok(pg.locator(".lk-recent button").count() >= 4, "recent look-ups, once the answer is closed")
    pg.locator(".lk-recent button").first.click(); pg.wait_for_timeout(1200)
    ok(pg.evaluate("!!S.lk.res"), "a recent look-up opens again")
    # Letters: tick, a contact typed, email opened, a reply that differs, reminders, settings
    pg.evaluate("() => { S.booksTab = 'letters'; S.ltr = null; window.__opened = []; window.open = (u) => { window.__opened.push(u); return null; }; render(); }"); pg.wait_for_timeout(800)
    n = pg.locator(".ltr-t tbody tr").count(); ok(n > 5, "parties with a balance on the year end: %d" % n)
    first = pg.locator(".ltr-t tbody tr").first.get_attribute("data-key")
    em = pg.locator(".ltr-t input[type=email]").first; em.fill("accounts@party.example"); pg.wait_for_timeout(1000)
    ok(pg.evaluate("S.books.letters.contacts[%s].email" % json.dumps(first)) == "accounts@party.example", "an email typed is kept")
    pg.locator(".ltr-t tbody tr").first.locator('button:text-is("Email")').click(); pg.wait_for_timeout(400)
    ok(any(u.startswith("mailto:accounts%40party.example") for u in pg.evaluate("window.__opened")) and pg.evaluate("!!S.books.letters.conf[S.ltr.asOn][%s].sentAt" % json.dumps(first)), "Email opens the user's mail, and the letter is marked sent")
    pg.locator(".ltr-t tbody tr").first.locator("input[type=checkbox]").check(); pg.wait_for_timeout(300)
    ok(pg.inner_text(".ltr-bar button.primary") == "Print or PDF the letters (1)", "a party ticked")
    pg.click(".ltr-bar button:nth-child(2)"); pg.wait_for_timeout(300)
    ok(pg.inner_text(".ltr-bar button:nth-child(2)") == "Untick all", "tick all")
    pg.locator('select[aria-label^="Reply from "]').first.select_option("differs"); pg.wait_for_timeout(400)
    pg.locator('input[aria-label="Their balance"]').first.fill("1000"); pg.wait_for_timeout(1400)
    ok("difference" in pg.inner_text(".ltr-t"), "a reply with a different figure shows the difference")
    mn = pg.locator('input[aria-label="Balances of at least"]'); mn.fill("100000"); mn.press("Tab"); pg.wait_for_timeout(500)
    ok(pg.locator(".ltr-t tbody tr").count() < n, "a minimum balance narrows the list")
    pg.click('.lk-kinds button:text-is("Dues reminders")'); pg.wait_for_timeout(700)
    ok(pg.locator(".ltr-t tbody tr").count() >= 1, "customers with overdue bills")
    pg.check('label.chk:has-text("MSMED") input'); pg.select_option('select[aria-label="Tone"]', "final"); pg.wait_for_timeout(300)
    ok("MSMED Act" in pg.evaluate("LTR.remindText(LTR.remindRows()[0]).body") and "Final reminder" in pg.evaluate("LTR.remindText(LTR.remindRows()[0]).subject"), "the MSME line and the tone")
    pg.click('.lk-kinds button:text-is("Letter settings")'); pg.wait_for_timeout(300)
    pg.fill('input[aria-label="Signed by (name and designation)"]', "A. Kumar, Partner"); pg.select_option('select[aria-label="Replies go to"]', "auditor"); pg.wait_for_timeout(1000)
    ok(pg.evaluate("[LTR.cfg().signer, LTR.cfg().replyTo]") == ["A. Kumar, Partner", "auditor"], "who signs, and replies to the auditor")
    # AI help: a suggestion accepted, one set by hand, a TDS ledger's section, notices, the settings
    pg.evaluate("""() => { S.firm.ai = {on: true}; const st = AIH.ledgerStats().filter(x => !AIH.ruleTds(x)).map(x => x.l), ls = [st[0], st[1], Object.keys(S.books.map).sort()[2]], R = RULE_DEFAULTS[0]; window.__ls = ls;
      S.books.ai = {led: {[ls[0]]: {tds: R.id, reason: 'staff welfare'}, [ls[1]]: {tds: 'none', reason: 'bank charges'}}, tdsPay: {[ls[2]]: {rule: R.id, reason: 'contracts'}}, pairs: {},
        notices: [{id: 'n1', kind: 'gst', name: 'asmt.pdf', at: '2026-02-02T00:00:00Z', by: 'a@b.in', step: 'drafted', reply: 'Dear Sir', fields: {form: 'ASMT-10'}}], log: []};
      S.booksTab = 'ledgers'; S.lmView = 'ai'; render(); }"""); pg.wait_for_timeout(600)
    ls = pg.evaluate("window.__ls")
    pg.click('tr[data-key=%s] button:text-is("Accept")' % json.dumps(ls[0])); pg.wait_for_timeout(400)
    ok(pg.evaluate("S.books.ai.led[%s].tdsOk" % json.dumps(ls[0])) == "yes" and "accepted by" in pg.inner_text('tr[data-key=%s]' % json.dumps(ls[0])), "a suggestion accepted, with who")
    pg.select_option('select[aria-label=%s]' % json.dumps("TDS section: " + ls[1]), "unsure"); pg.wait_for_timeout(400)
    ok(pg.evaluate("[S.books.ai.led[%s].tds, S.books.ai.led[%s].byHand]" % (json.dumps(ls[1]), json.dumps(ls[1]))) == ["unsure", True], "a section set by hand")
    pg.click('tr:has(td:text-is(%s)) button:text-is("Accept")' % json.dumps(ls[2])); pg.wait_for_timeout(400)
    ok(pg.evaluate("S.books.map[%s].section" % json.dumps(ls[2])) and pg.evaluate("!S.books.ai.tdsPay[%s]" % json.dumps(ls[2])), "a TDS ledger's section accepted")
    pg.evaluate("() => { S.booksTab = 'audit'; S.auditTab = 'find'; render(); }"); pg.wait_for_timeout(500)
    pg.click('button:has-text("AI review of ledgers")'); pg.wait_for_timeout(500)
    ok(pg.evaluate("[S.booksTab, S.lmView]") == ["ledgers", "ai"], "the Audit button opens the AI review")
    pg.evaluate("() => { S.booksTab = 'gst'; S.gstPart = 'notices'; render(); }"); pg.wait_for_timeout(500)
    ta = pg.locator('textarea[aria-label="Draft reply"]'); ta.fill("Dear Sir, corrected."); ta.press("Tab"); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.books.ai.notices[0].reply") == "Dear Sir, corrected.", "the draft reply, corrected, is kept")
    pg.click('.dash-card[data-key="n1"] button:text-is("remove")'); pg.wait_for_timeout(300)
    ok(pg.locator("#confirmBox .cbx").is_visible(), "removing a notice asks first")
    pg.click('#confirmBox button[data-cbx="yes"]'); pg.wait_for_timeout(600)
    ok(pg.evaluate("S.books.ai.notices.length") == 0, "and removes it")
    pg.evaluate("() => { S.view = 'home'; S.homeTab = 'rules'; S.settingsTab = 'ai'; render(); }"); pg.wait_for_timeout(500)
    pg.uncheck('label:has-text("Use AI help") input'); pg.wait_for_timeout(300)
    ok(pg.evaluate("AIH.cfg().on") is False and pg.locator('label:has-text("notices") input').first.is_disabled(), "AI help switched off, each kind greyed")
    pg.check('input[aria-label="AI off for ZZ TEST"]'); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.companies[S.coId].aiOff") is True, "a client kept away from AI")
    pg.click('#app [data-confirm-foot] [data-cfm="save"]'); pg.wait_for_timeout(300)   # review 18: the firm's AI settings saved with Save
    pg.evaluate("() => { S.firm.ai = {on: false}; S.companies[S.coId].aiOff = false; S.view = 'company'; S.tab = 'books'; render(); }"); pg.wait_for_timeout(300)
    # Accounts: run, the format, stock, a manufacturer, a ledger placed by hand and back, the search, Excel
    pg.evaluate("() => { const led = {}; Object.keys(S.books.map).forEach(n => { led[n] = {open: 0, close: 0}; }); S.books.tb = {from: '20250401', to: '20270331', at: '2026-01-01T00:00:00Z', led}; S.booksTab = 'fs'; S.fsRun = null; render(); }"); pg.wait_for_timeout(400)
    run = 'section[data-fs-head] button:text-is("Run now")'
    pg.click(run); pg.wait_for_timeout(1500)
    ok("The balance sheet tallies." in pg.inner_text("#app") and "Schedule III" in pg.inner_text("#app"), "Run now: Schedule III statements, tallied")
    pg.select_option('select[aria-label="Format"]', "nc"); pg.wait_for_timeout(300)
    pg.wait_for_timeout(1500)   # the year runs by itself again for the new format (review of 01-Oct-2026, item 12)
    ok(pg.evaluate("FS.cfg(S.books).kind") == "nc" and ("Press Run now." in pg.inner_text("#app") or "Non-Corporate" in pg.inner_text("#app")), "another format: asks for a new run, or runs it by itself")
    pg.evaluate("document.querySelectorAll('#app details').forEach(d => d.open = true)")
    box = pg.locator('input[aria-label="Closing stock"]'); box.fill("2500"); box.press("Tab"); pg.wait_for_timeout(300)
    ok(pg.evaluate("FS.cfg(S.books).stock.close") == 2500, "closing stock is kept")
    pg.evaluate("document.querySelectorAll('#app details').forEach(d => d.open = true)")
    pg.check('label:has-text("materials consumed") input'); pg.wait_for_timeout(200)
    ok(pg.evaluate("FS.cfg(S.books).mfg") is True, "a manufacturer is kept")
    pg.click(run); pg.wait_for_timeout(1500)
    ok("Non-Corporate" in pg.inner_text("#app"), "the non-corporate format")
    pg.click('nav[aria-label="Accounts"] button:text-is("Mapping")'); pg.wait_for_timeout(600)
    sel = pg.locator('select[aria-label^="Goes to: "]').first; l = sel.get_attribute("aria-label")[9:]
    sel.select_option("oca"); pg.wait_for_timeout(1500)
    ok(pg.evaluate("S.books.fs.map[%s]" % json.dumps(l)) == "oca" and pg.locator('tr[data-key=%s] .tag:text-is("by hand")' % json.dumps(l)).count() == 1, "a ledger placed by hand: " + l)
    pg.click('tr[data-key=%s] button:text-is("by rule")' % json.dumps(l)); pg.wait_for_timeout(1500)
    ok(l not in pg.evaluate("Object.keys(S.books.fs.map)"), "and back to the rule")
    pg.fill("#fsq", l[:4]); pg.wait_for_timeout(600)
    ok(pg.evaluate("document.activeElement.id") == "fsq" and all(l[:4].lower() in k.lower() for k in pg.locator("tr[data-key]").evaluate_all("rs => rs.map(r => r.dataset.key)")), "the ledger search, keeping the cursor")
    pg.evaluate("() => { window.__saved = []; window.saveFile = (n) => window.__saved.push(n); }")
    pg.click('section[data-fs-head] button:text-is("Excel")'); pg.wait_for_timeout(3000)
    ok(any("financial-statements" in n for n in pg.evaluate("window.__saved")), "as Excel")
    ok(not errors, "no page errors" + ("" if not errors else ": " + errors[0]))
    br.close()
srv.shutdown()
print("\nall passed" if not fails else "\nFAILED: %d" % len(fails)); raise SystemExit(1 if fails else 0)
