"""python3 run_react_booktabs.py - the Books tabs other than TDS and GST in React, with the books in tests/data: Tally
ledgers (a meaning set, confirmed and undone, the find box, confirm the shown, the posting ledgers), and more as they
move. Run on the React build: TDSDESK_SITE=../app/dist-test python3 run_react_booktabs.py"""
import json, os, threading, functools, http.server
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers")
from playwright.sync_api import sync_playwright
H = functools.partial(http.server.SimpleHTTPRequestHandler, directory=os.environ.get("TDSDESK_SITE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "dist-test"))); H.log_message = lambda *a: None
srv = http.server.ThreadingHTTPServer(("localhost", 8158), H); threading.Thread(target=srv.serve_forever, daemon=True).start()
books = json.load(open(os.environ.get("TDSDESK_CACHE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "books-cache.json"))))
fails, errors = [], []
def ok(c, w):
    print(("  ok   " if c else "  FAIL ") + w)
    if not c: fails.append(w)
with sync_playwright() as p:
    br = p.chromium.launch(); pg = br.new_page(viewport={"width": 1400, "height": 1000}); pg.on("pageerror", lambda e: errors.append(str(e)))
    pg.goto("http://localhost:8158/"); pg.wait_for_timeout(2500); pg.click('button[data-act="useOffline"]'); pg.wait_for_timeout(1500)
    pg.evaluate("""(bk) => { const c = newCompany({name: "ZZ TEST", gstin: "09AANFG3202D1ZR"}); S.companies[c.id] = c; S.coId = c.id; S.view = "company"; S.tab = "books"; S.loadingCo = false;
      S.books = Object.assign({loading: false, challans: [], alloc: {}}, bk, {cid: c.id}); S.books.map = Books.mapLedgers(bk.vouchers, {}); LedMaster.refresh(S.books); window.__bk = S.books; S.booksTab = "ledgers"; render(); }""", books)
    pg.wait_for_timeout(1200); pg.evaluate("S.books = window.__bk; render();"); pg.wait_for_timeout(600)
    # Tally ledgers
    pend = lambda: pg.evaluate("LedMaster.pending(S.books).length")
    n0 = pend()
    ok(n0 > 0 and pg.locator("#lmTable tbody tr").count() == n0, "Tally ledgers: the %d to confirm are listed" % n0)
    row = pg.locator("#lmTable tbody tr").first; name = row.get_attribute("data-key")
    row.locator("td.ac button").click(); pg.wait_for_timeout(400)
    ok(pend() == n0 - 1 and pg.evaluate("S.books.map[%s].ok" % json.dumps(name)), "Confirm: %s confirmed, one fewer to confirm" % name)
    pg.click('nav[aria-label="Ledgers"] button:has-text("Confirmed")'); pg.wait_for_timeout(400)
    pg.locator('#lmTable tr[data-key=%s] button:text-is("✓ confirmed")' % json.dumps(name)).click(); pg.wait_for_timeout(400)
    ok(pend() == n0 and not pg.evaluate("S.books.map[%s].ok" % json.dumps(name)), "✓ confirmed, clicked: undone")
    pg.click('nav[aria-label="Ledgers"] button:has-text("Other ledgers")'); pg.wait_for_timeout(400)
    other = pg.locator("#lmTable tbody tr").first.get_attribute("data-key")
    box = pg.locator('input[aria-label="Find a ledger"]'); box.click(); pg.keyboard.type(other[:8], delay=15); pg.wait_for_timeout(600)
    ok(pg.evaluate("document.activeElement.getAttribute('aria-label')") == "Find a ledger" and pg.locator("#lmTable tbody tr").count() >= 1, "the find box filters as typed, keeping the cursor")
    pg.select_option('select[aria-label="What %s is"]' % other, "tds_payable"); pg.wait_for_timeout(500)
    m = pg.evaluate("S.books.map[%s]" % json.dumps(other))
    ok(m["what"] == "tds_payable" and m["ok"], "an other ledger made a TDS ledger: kept, and confirmed as the user's own choice")
    box.fill(""); pg.click('nav[aria-label="Ledgers"] button:has-text("TDS and TCS")'); pg.wait_for_timeout(400)
    sec = pg.locator('input[aria-label="Section of %s"]' % other); sec.fill("194j"); sec.press("Tab"); pg.wait_for_timeout(400)
    ok(pg.evaluate("S.books.map[%s].section" % json.dumps(other)) == "194J", "its section typed, kept in capitals")
    pg.click('nav[aria-label="Ledgers"] button:has-text("To confirm")'); pg.wait_for_timeout(400)
    pg.click('button:has-text("Confirm the")'); pg.wait_for_timeout(600)
    ok(pend() == 0 and "Every GST and TDS ledger is confirmed." in pg.inner_text("#app"), "Confirm the shown: nothing left to confirm")
    pg.click('nav[aria-label="Ledgers"] button:has-text("What FinCom posts to")'); pg.wait_for_timeout(400)
    ok("What FinCom posts bills to" in pg.inner_text("#app"), "What FinCom posts to: the posting ledgers")
    # Audit: run, open a finding, its status and note, an area, related parties, the 3CD draft
    pg.evaluate("() => { S.booksTab = 'audit'; S.books.stale = {}; render(); }"); pg.wait_for_timeout(500)
    pg.fill('input[aria-label="Audit from"]', "2025-04-01"); pg.fill('input[aria-label="Audit to"]', "2026-03-31")
    pg.click('button:text-is("Run now")'); pg.wait_for_timeout(3000)
    run = pg.evaluate("S.books.audit && S.books.audit.last && {n: S.books.audit.last.findings.length, from: S.books.audit.last.from}")
    ok(run and run["n"] > 0 and run["from"] == "20250401", "Run now: findings for the period chosen (%s)" % run)
    fid = pg.evaluate("S.books.audit.last.findings[0].id")
    sec = 'section[data-key=%s]' % json.dumps(fid)
    pg.click(sec + ' > .row button.linkbtn'); pg.wait_for_timeout(400)
    ok("Effect." in pg.inner_text(sec), "a finding opens: its effect and what to do")
    pg.select_option(sec + ' > .row select', "pass"); pg.wait_for_timeout(400)
    note = pg.locator(sec + ' input[aria-label="Note for the report"]'); note.fill("to reverse"); note.press("Tab"); pg.wait_for_timeout(400)
    st = pg.evaluate("S.books.audit.st[%s]" % json.dumps(fid))
    ok(st["s"] == "pass" and st["note"] == "to reverse", "its status and note are kept")
    pg.select_option('select[aria-label="Run on its own"]', "weekly"); pg.wait_for_timeout(300)
    ok(pg.evaluate("Audit.cfg(S.books).freq") == "weekly", "how often it runs by itself is kept")
    pg.click('nav[aria-label="Audit"] button:text-is("Related parties")'); pg.wait_for_timeout(400)
    led = pg.evaluate("Object.keys(S.books.map).sort()[0]")
    pg.fill("#relq", led); pg.click('.row:has(#relq) button:text-is("Add")'); pg.wait_for_timeout(400)
    pg.select_option('select[aria-label="Relation of %s"]' % led, "Director"); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.books.auditRel") == [{"name": led, "relation": "Director"}], "a related party added from the list, with its relation")
    pg.click('tr[data-key=%s] button:text-is("remove")' % json.dumps(led)); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.books.auditRel.length") == 0, "and removed")
    pg.click('nav[aria-label="Audit"] button:text-is("Form 3CD draft")'); pg.wait_for_timeout(600)
    ok(pg.locator(".audit3cd table").count() > 0, "the Form 3CD draft, filled from the run")
    # MIS: a quick period, run now, the tabs, a party opened and filtered, a supplier marked MSME, a budget month, how often
    pg.evaluate("() => { S.booksTab = 'mis'; S.books.mis = null; S.misRange = null; S.books.stale = {}; render(); }"); pg.wait_for_timeout(500)
    pg.click('button:text-is("Last year")'); pg.wait_for_timeout(300)
    rg = pg.evaluate("S.misRange"); ok(pg.input_value('input[aria-label="MIS from"]') == rg["from"], "a quick period fills the dates (%s)" % rg)
    pg.fill('input[aria-label="MIS from"]', "2026-04-01"); pg.fill('input[aria-label="MIS to"]', "2026-06-30"); pg.wait_for_timeout(200)
    pg.click('section:has(> h3:text-is("MIS")) button:text-is("Run now")'); pg.wait_for_timeout(3000)
    r = pg.evaluate("S.books.mis && S.books.mis.last && {from: S.books.mis.last.from, to: S.books.mis.last.to}")
    ok(r == {"from": "20260401", "to": "20260630"}, "Run now: the MIS for the dates typed (%s)" % r)
    ok("Sales, the period" in pg.inner_text("#app"), "the summary")
    pg.click('nav[aria-label="MIS"] button:text-is("Receivables")'); pg.wait_for_timeout(400)
    party = pg.locator("#misAge tbody tr[data-key]").first.get_attribute("data-key")
    pg.click('#misAge tr[data-key=%s] button.linkbtn' % json.dumps(party)); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.misOpen") == party and pg.locator("#misAge th:text-is('Outstanding')").count() == 1, "a customer opens to its bills")
    pg.fill("#misq", party[:5]); pg.wait_for_timeout(600)
    ok(all(party[:5].lower() in (x or "").lower() for x in pg.locator("#misAge tbody tr[data-key]").evaluate_all("rs => rs.map(r => r.dataset.key)")), "the search keeps only matching customers")
    ok(pg.evaluate("document.activeElement.id") == "misq", "the search box keeps the cursor")
    pg.click('nav[aria-label="MIS"] button:text-is("Payables")'); pg.wait_for_timeout(400)
    ok(pg.input_value("#misq") == "", "a new tab starts with no search")
    sel = pg.locator('select[aria-label^="MSME: "]').first; sup = sel.get_attribute("aria-label")[6:]
    sel.select_option("Micro"); pg.wait_for_timeout(1500)
    ok(pg.evaluate("S.books.msme[%s]" % json.dumps(sup)) == "Micro", "a supplier marked micro is kept")
    pg.select_option('select[aria-label="Which parties"]', "msme"); pg.wait_for_timeout(400)
    ok(pg.locator("#misAge tbody tr[data-key]").count() >= 1, "and shows under MSME suppliers")
    pg.click('nav[aria-label="MIS"] button:text-is("Profit and loss")'); pg.wait_for_timeout(400)
    n = pg.evaluate("S.books.mis.last.pl.heads.exp.led.length")
    pg.click('#misPl button:text-is("\u25b8 %d ledgers")' % n); pg.wait_for_timeout(300)
    led = pg.evaluate("S.books.mis.last.pl.heads.exp.led[0].l")
    pg.locator("#misPl button.linkbtn").filter(has_text=led).first.click(); pg.wait_for_timeout(400)
    ok(pg.locator("h3").filter(has_text=led).count() == 1, "a ledger's entries open from the profit and loss")
    pg.click('nav[aria-label="MIS"] button:text-is("Cash flow")'); pg.wait_for_timeout(400)
    pg.click("#misFc tbody tr:first-child button.linkbtn"); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.misWeek") == 0 and pg.locator("#misFc th:text-is('Why this date')").count() == 1, "a week of the forecast opens")
    pg.click('nav[aria-label="MIS"] button:text-is("Budget")'); pg.wait_for_timeout(400)
    box = pg.locator('input[aria-label="Budget Revenue from operations Apr 2026"]')
    box.fill("250000"); box.press("Tab"); pg.wait_for_timeout(500)
    ok(pg.evaluate("S.books.budget['2026'].rev['202604']") == 250000, "a budget month is kept")
    ok("2,50,000.00" in pg.inner_text("#app"), "and the year's total follows")
    pg.select_option('select[aria-label="MIS runs on its own"]', "weekly"); pg.wait_for_timeout(300)
    ok(pg.evaluate("MIS.cfg(S.books).freq") == "weekly", "how often the MIS runs by itself is kept")
    # Accounts: run, the format, stock, a manufacturer, a ledger placed by hand and back, the search, Excel
    pg.evaluate("() => { const led = {}; Object.keys(S.books.map).forEach(n => { led[n] = {open: 0, close: 0}; }); S.books.tb = {from: '20250401', to: '20270331', at: '2026-01-01T00:00:00Z', led}; S.booksTab = 'fs'; S.fsRun = null; render(); }"); pg.wait_for_timeout(400)
    run = 'section:has(> h3:text-is("Financial statements")) button:text-is("Run now")'
    pg.click(run); pg.wait_for_timeout(1500)
    ok("The balance sheet tallies." in pg.inner_text("#app") and "Schedule III" in pg.inner_text("#app"), "Run now: Schedule III statements, tallied")
    pg.select_option('select[aria-label="Format"]', "nc"); pg.wait_for_timeout(300)
    ok(pg.evaluate("FS.cfg(S.books).kind") == "nc" and "Press Run now." in pg.inner_text("#app"), "another format asks for a new run")
    box = pg.locator('input[aria-label="Closing stock"]'); box.fill("2500"); box.press("Tab"); pg.wait_for_timeout(300)
    ok(pg.evaluate("FS.cfg(S.books).stock.close") == 2500, "closing stock is kept")
    pg.check('label:has-text("materials consumed") input'); pg.wait_for_timeout(200)
    ok(pg.evaluate("FS.cfg(S.books).mfg") is True, "a manufacturer is kept")
    pg.click(run); pg.wait_for_timeout(1500)
    ok("Non-Corporate" in pg.inner_text("#app"), "the non-corporate format")
    pg.click('nav[aria-label="Accounts"] button:text-is("Mapping")'); pg.wait_for_timeout(600)
    sel = pg.locator('select[aria-label^="Goes to: "]').first; l = sel.get_attribute("aria-label")[9:]
    sel.select_option("oca"); pg.wait_for_timeout(1500)
    ok(pg.evaluate("S.books.fs.map[%s]" % json.dumps(l)) == "oca" and pg.locator('tr[data-key=%s] .tag:text-is("by hand")' % json.dumps(l)).count() == 1, "a ledger placed by hand: " + l)
    pg.click('tr[data-key=%s] button:text-is("by rule")' % json.dumps(l)); pg.wait_for_timeout(1500)
    ok(l not in pg.evaluate("Object.keys(S.books.fs.map)"), "and back to the rule")
    pg.fill("#fsq", l[:4]); pg.wait_for_timeout(600)
    ok(pg.evaluate("document.activeElement.id") == "fsq" and all(l[:4].lower() in k.lower() for k in pg.locator("tr[data-key]").evaluate_all("rs => rs.map(r => r.dataset.key)")), "the ledger search, keeping the cursor")
    pg.evaluate("() => { window.__saved = []; window.saveFile = (n) => window.__saved.push(n); }")
    pg.click('section:has(> h3:text-is("Financial statements")) button:text-is("Excel")'); pg.wait_for_timeout(3000)
    ok(any("financial-statements" in n for n in pg.evaluate("window.__saved")), "as Excel")
    ok(not errors, "no page errors" + ("" if not errors else ": " + errors[0]))
    br.close()
srv.shutdown()
print("\nall passed" if not fails else "\nFAILED: %d" % len(fails)); raise SystemExit(1 if fails else 0)
