"""python3 run_mis_ui.py - the MIS tab in a browser."""
import json, os, sys, threading, functools, http.server
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers")
from playwright.sync_api import sync_playwright
H = functools.partial(http.server.SimpleHTTPRequestHandler, directory=os.environ.get("TDSDESK_SITE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "site-test"))); H.log_message = lambda *a: None
srv = http.server.ThreadingHTTPServer(("localhost", 8130), H); threading.Thread(target=srv.serve_forever, daemon=True).start()
OUT = os.environ.get("TDSDESK_OUT", os.path.join(os.path.dirname(os.path.abspath(__file__)), "out"))
books = json.load(open(os.environ.get("TDSDESK_CACHE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "books-cache.json"))))
fails, errors = [], []
def ok(c, w):
    print(("  ok   " if c else "  FAIL ") + w)
    if not c: fails.append(w)
with sync_playwright() as p:
    br = p.chromium.launch(); ctx = br.new_context(viewport={"width": 1400, "height": 1000}); pg = ctx.new_page()
    pg.on("pageerror", lambda e: errors.append(str(e)))
    pg.goto("http://localhost:8130/"); pg.wait_for_timeout(2500)
    pg.click('button[data-act="useOffline"]'); pg.wait_for_timeout(1500)
    pg.evaluate("""(bk) => { const c = newCompany({name: "ZZ TEST (VMS books)", gstin: "07AADCV3366N1ZU"}); S.companies[c.id] = c; S.coId = c.id; S.view = "company"; S.tab = "books"; S.loadingCo = false;
      S.books = Object.assign({loading: false, challans: [], alloc: {}}, bk, {cid: c.id, misCfg: {freq: "off"}, auditCfg: {freq: "off"}}); S.books.map = Books.mapLedgers(bk.vouchers, {}); window.__bk = S.books; S.booksTab = "import"; render(); }""", books)
    pg.wait_for_timeout(1200); pg.evaluate("S.books = window.__bk; render();"); pg.wait_for_timeout(600)
    pg.set_input_files("#mastersIn", os.path.join(os.environ.get("TDSDESK_DATA", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")), "Master.xml")); pg.wait_for_timeout(12000)
    pg.evaluate("S.booksTab = 'mis'; render();"); pg.wait_for_timeout(500)
    t = pg.inner_text("#app")
    ok("Run now" in t and "Year to date" in t and "Last month" in t, "period picker, quick periods and Run now are always there")
    pg.click('button[data-misquick="lastyear"]'); pg.wait_for_timeout(300)
    ok(pg.evaluate("S.misRange.from") == "2025-04-01" and pg.evaluate("S.misRange.to") == "2026-03-31", "Last year sets 1 Apr 2025 to 31 Mar 2026")
    pg.click('button[data-act="misRun"]'); pg.wait_for_timeout(3000)
    t = pg.inner_text("#app")
    ok("sales, the period" in t.lower() and "56,39,22,176.16" in t, "summary: sales for the year")
    ok("settled against older bills" in t, "says plainly that receivables miss bills from before the books")
    pg.screenshot(path=OUT + "/mis-summary.png", full_page=True)
    pg.click('button[data-mistab="pl"]'); pg.wait_for_timeout(500)
    t = pg.inner_text("#app")
    ok("Gross profit" in t and "Profit before tax" in t and "Apr 2025" in t and "Mar 2026" in t, "profit and loss, month by month")
    pg.click('button[data-misopenhead="exp"]'); pg.wait_for_timeout(400)
    led = pg.locator("button[data-misled]").first.get_attribute("data-misled")
    pg.click('button[data-misled="%s"]' % led.replace('"', '\\"')); pg.wait_for_timeout(500)
    ok(led in pg.inner_text("#app") and "Narration" in pg.inner_text("#app").title(), "a ledger opens to its vouchers: " + led)
    pg.screenshot(path=OUT + "/mis-pl.png", full_page=False)
    pg.click('button[data-mistab="recv"]'); pg.wait_for_timeout(500)
    pg.select_option("select[data-misf]", "90"); pg.wait_for_timeout(400)
    rows = pg.locator("#misAge > tbody > tr").count()
    ok(rows >= 2, "receivables: over 90 days filter (%d rows)" % rows)
    party = pg.locator("button[data-misopen]").first.get_attribute("data-misopen")
    pg.click('button[data-misopen="%s"]' % party); pg.wait_for_timeout(400)
    ok("Outstanding" in pg.inner_text("#app").title() or pg.locator("#misAge table").count() == 1, "a customer opens to its bills")
    pg.click('button[data-mistab="pay"]'); pg.wait_for_timeout(500)
    pg.select_option("select[data-misf]", "msme"); pg.wait_for_timeout(400)
    t = pg.inner_text("#app")
    ok("MSME suppliers unpaid past 45 days" in t, "payables: MSME past 45 days, section 43B(h)")
    sel = pg.locator("select[data-mismsme]").first; sup = sel.get_attribute("data-mismsme")
    pg.select_option("select[data-misf]", ""); pg.wait_for_timeout(300)
    pg.locator('select[data-mismsme]').nth(3).select_option("Micro"); pg.wait_for_timeout(1500)
    ok(len([v for v in pg.evaluate("Object.values(S.books.msme)") if v == "Micro"]) == 1, "a supplier marked MSME by hand")
    pg.click('button[data-mistab="sales"]'); pg.wait_for_timeout(500)
    ok("Top five customers" in pg.inner_text("#app"), "sales by customer")
    pg.click('button[data-mistab="purch"]'); pg.wait_for_timeout(500)
    ok("Expense heads by month" in pg.inner_text("#app") and "jumped" in pg.inner_text("#app"), "purchases and expense heads, with jumps")
    pg.click('button[data-mistab="comp"]'); pg.wait_for_timeout(500)
    ok("GST by month" in pg.inner_text("#app") and "TDS by month" in pg.inner_text("#app"), "compliance")
    # a month, then the pack
    pg.fill("input[data-misfrom]", "2025-06-01"); pg.dispatch_event("input[data-misfrom]", "change")
    pg.fill("input[data-misto]", "2025-06-30"); pg.dispatch_event("input[data-misto]", "change")
    pg.click('button[data-act="misRun"]'); pg.wait_for_timeout(2500)
    ok(pg.evaluate("S.books.mis.last.from") == "20250601" and pg.evaluate("S.books.mis.last.prev.sales") > 0, "June, compared with May")
    with ctx.expect_page() as pop:
        pg.click('button[data-act="misPack"]')
    rp = pop.value; rp.wait_for_timeout(800); rt = rp.inner_text("body")
    ok("At a glance" in rt and "Profit and loss" in rt and "Receivables, largest 15" in rt and "Due in the coming weeks" in rt, "the MIS pack")
    rp.pdf(path=OUT + "/mis-pack.pdf"); rp.close()
    pg.evaluate("() => { window.__saved = []; window.saveFile = (n) => window.__saved.push(n); }")
    pg.click('button[data-act="misExcel"]'); pg.wait_for_timeout(3000)
    ok(any("-MIS-" in n for n in pg.evaluate("window.__saved")), "Excel")
    # on its own, monthly: runs for the month just ended
    pg.select_option("select[data-misfreq]", "monthly"); pg.wait_for_timeout(300)
    pg.evaluate("S.books.mis.last.at = '2026-08-01T09:00:00.000Z'; MIS.maybeRun(); render();"); pg.wait_for_timeout(2500)
    ok(pg.evaluate("S.books.mis.last.how").startswith("on its own") and pg.evaluate("S.books.mis.last.from") == "20260301" and pg.evaluate("S.books.mis.last.to") == "20260331", "on its own, monthly: the month just ended, or the last month in the books: " + pg.evaluate("S.books.mis.last.from + '-' + S.books.mis.last.to"))
    bad = pg.evaluate("""() => { const bad = []; ['summary', 'pl', 'recv', 'pay', 'sales', 'purch', 'comp'].forEach(tb => { S.misTab = tb; try { render(); } catch (e) { bad.push(tb + ': ' + e.message); } }); return bad; }""")
    ok(not bad, "every tab renders" + ("" if not bad else ": " + "; ".join(bad)))
    br.close()
errs = [e for e in errors if "supabase" not in e and "Failed to load" not in e]
ok(not errs, "no page errors" + ("" if not errs else ": " + " | ".join(errs[:4])))
print("\n" + ("%d FAILED" % len(fails) if fails else "all passed")); sys.exit(1 if fails else 0)
