"""python3 run_react_bill.py - purchase bills in React: the list and a bill, typed in and changed like a user would.
Offline, a made-up client; no client data needed.
Run on the React build: TDSDESK_SITE=../app/dist-test python3 run_react_bill.py"""
import os, threading, functools, http.server
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers")
from playwright.sync_api import sync_playwright
H = functools.partial(http.server.SimpleHTTPRequestHandler, directory=os.environ.get("TDSDESK_SITE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "dist-test"))); H.log_message = lambda *a: None
srv = http.server.ThreadingHTTPServer(("localhost", 8154), H); threading.Thread(target=srv.serve_forever, daemon=True).start()
OUT = os.environ.get("TDSDESK_OUT", "out"); os.makedirs(OUT, exist_ok=True); fails, errors = [], []
def ok(c, w):
    print(("  ok   " if c else "  FAIL ") + w)
    if not c: fails.append(w)
with sync_playwright() as p:
    br = p.chromium.launch(); pg = br.new_page(viewport={"width": 1400, "height": 950}); pg.on("pageerror", lambda e: errors.append(str(e)))
    pg.goto("http://localhost:8154/"); pg.wait_for_timeout(2500); pg.click('button[data-act="useOffline"]'); pg.wait_for_timeout(1200)
    cid = pg.evaluate("""() => { const c = newCompany({name: "ZZ Zeta Exports", gstin: "09AANFG3202D1ZR"}); S.companies[c.id] = c; S.data[c.id] = {parties: {}, entries: {}, loaded: true}; c.stats = {}; return c.id; }""")
    pg.evaluate("(cid) => openCompany(cid).then(() => goStep('review', 'bills'))", cid); pg.wait_for_timeout(1200)
    app = lambda: pg.inner_text("#app")
    # Purchase opens on the review table (an old screen still); “One at a time” is the list with the bill beside it
    pg.click('#app button:has-text("One at a time")'); pg.wait_for_timeout(600)
    E = lambda k: pg.evaluate("(k) => { const e = D().entries[S.selected]; return k ? (k in e.x ? e.x[k] : e[k]) : e; }", k)
    ok("No bills yet for ZZ Zeta Exports" in app(), "no bills: the upload box says so")
    # a bill typed in
    pg.evaluate("doAct('manual')"); pg.wait_for_timeout(800)
    ok(pg.locator("#app .detail h2").inner_text() == "New invoice" and pg.locator("#app .queue li").count() == 1, "Type an invoice: a new draft, open beside the list")
    name = pg.locator('#app label:has-text("Supplier name") input')
    name.click(); pg.keyboard.type("ZZ Consulting LLP", delay=15); pg.wait_for_timeout(700)
    ok(E("vendorName") == "ZZ Consulting LLP" and name.input_value() == "ZZ Consulting LLP", "typing the supplier: kept on the bill and in the box")
    ok(pg.evaluate("document.activeElement === document.querySelector('#app label:nth-of-type(1) input') || document.activeElement.closest('label').innerText.startsWith('Supplier')"), "the cursor stays in the box through the redraw that follows")
    ok(E("partyLedger") == "ZZ Consulting LLP", "the party ledger follows the supplier's name")
    ok(pg.locator("#app .detail h2").inner_text() == "ZZ Consulting LLP" and "ZZ Consulting LLP" in pg.inner_text("#app .queue"), "the heading and the list follow")
    pg.fill('#app label:has-text("GSTIN") >> nth=0 >> input', "09aaacz1234a1z5"); pg.wait_for_timeout(500)
    ok(E("vendorGstin") == "09AAACZ1234A1Z5", "a GSTIN is kept in capitals")
    pg.fill('#app label:has-text("Invoice no.") input', "ZC/77")
    pg.fill('#app label:has-text("Invoice date") input', "2026-09-10"); pg.wait_for_timeout(400)
    ok(E("invoiceDate") == "2026-09-10" and E("invoiceNo") == "ZC/77", "invoice number and date")
    pg.fill('#app label:has-text("Taxable value") input', "100000"); pg.fill('#app label:has-text("IGST") input', "18000"); pg.fill('#app label:has-text("Invoice total") input', "118000"); pg.wait_for_timeout(700)
    ok(str(E("taxable")) == "100000" and str(E("total")) == "118000", "amounts")
    # the TDS decision
    pg.select_option('#app label:has-text("Payment type") select', "professional"); pg.wait_for_timeout(600)
    want = pg.evaluate("compute(D().entries[S.selected]).tds")
    verdict = pg.inner_text("#app .verdict")
    ok(E("natureId") == "professional" and want > 0 and ("TDS applies: " + pg.evaluate("(n) => money(n)", want)) in verdict, "Professional fees: TDS applies, the same figure the rules work out (" + verdict + ")")
    ok("393(1) Sl. 6(iii)(a)" in pg.inner_text("#app dl.figs") and "194J" in pg.inner_text("#app dl.figs"), "the section, new and old")
    pg.click('#app label:has-text("Deduct TDS on this bill") input'); pg.wait_for_timeout(600)
    ok("not booked" in pg.inner_text("#app .verdict") and pg.locator('#app label:has-text("Why not") select').count() == 1, "untick Deduct TDS: not booked, and a reason is asked")
    pg.select_option('#app label:has-text("Why not") select', index=1); pg.wait_for_timeout(400)
    ok(bool(E("tdsSkip")), "the reason is kept")
    pg.click('#app label:has-text("Deduct TDS on this bill") input'); pg.wait_for_timeout(600)
    ok("not booked" not in pg.inner_text("#app .verdict") and pg.is_checked('#app label:has-text("Deduct TDS on this bill") input'), "tick it again: booked")
    # GST
    pg.click('#app label:has-text("Reverse charge applies") input'); pg.wait_for_timeout(600)
    ok(pg.evaluate("D().entries[S.selected].rcm.on") is True and "Tax payable under reverse charge" in app(), "reverse charge on: the tax it makes")
    pg.click('#app label:has-text("Reverse charge applies") input'); pg.wait_for_timeout(600)
    ok(pg.evaluate("D().entries[S.selected].rcm.on") is False and "Tax payable under reverse charge" not in app(), "and off")
    pg.click('#app label:has-text("GST credit is blocked") input'); pg.wait_for_timeout(600)
    ok(pg.evaluate("D().entries[S.selected].itcBlock.on") is True and "is added to the expense instead of input credit" in app(), "blocked credit: GST goes to the expense")
    pg.click('#app label:has-text("GST credit is blocked") input'); pg.wait_for_timeout(400)
    # the draft entry for Tally
    exp = pg.locator('#app input[aria-label="Expense ledger"]')
    ok(exp.get_attribute("data-ac") == "1" and exp.input_value() == pg.evaluate("D().entries[S.selected].expenseLedger"), "the expense ledger: a box with the Tally ledger list, showing the bill's ledger")
    exp.fill("Legal and Professional Charges"); pg.wait_for_timeout(700)
    ok(E("expenseLedger") == "Legal and Professional Charges" and "Legal and Professional Charges" == exp.input_value(), "typing a ledger keeps it")
    rows = pg.locator("#app table.vtbl tbody tr").count()
    dr, cr = pg.inner_text("#app table.vtbl tfoot td:nth-child(3)"), pg.inner_text("#app table.vtbl tfoot td:nth-child(4)")
    ok(rows >= 3 and dr == cr, "the entry balances: debit " + dr + " = credit " + cr)
    narr = pg.locator('#app label:has-text("Narration") input')
    narr.fill("Consulting for Sept"); pg.wait_for_timeout(700)
    ok(E("narration") == "Consulting for Sept" and narr.input_value() == "Consulting for Sept", "narration")
    pg.screenshot(path=OUT + "/react-bill.png", full_page=True)
    # a second bill, and the list
    pg.evaluate("doAct('manual')"); pg.wait_for_timeout(700)
    ok(pg.locator("#app .queue li").count() == 2 and pg.locator("#app .detail h2").inner_text() == "New invoice", "a second bill: two in the list, the new one open")
    pg.click('#app .queue button:has-text("ZZ Consulting LLP")'); pg.wait_for_timeout(500)
    ok(pg.locator("#app .detail h2").inner_text() == "ZZ Consulting LLP" and pg.get_attribute('#app .queue button:has-text("ZZ Consulting LLP")', "aria-current") == "true", "a click on the list opens that bill")
    ok(pg.locator('#app button:has-text("Review all 2 in a table")').count() == 1, "“Review all 2 in a table”")
    pg.click('#app .filters button:has-text("Approved")'); pg.wait_for_timeout(500)
    ok("Nothing approved yet." in app() and "Select an invoice" in app(), "Approved: nothing yet")
    pg.click('#app .filters button:has-text("To review")'); pg.wait_for_timeout(500)
    # approve (the bar at the bottom, still an old screen) and see it read-only
    pg.click('#app .queue button:has-text("ZZ Consulting LLP")'); pg.wait_for_timeout(400)
    pg.evaluate("approve(D().entries[S.selected]); refreshStats(S.coId); render()"); pg.wait_for_timeout(600)
    pg.click('#app .filters button:has-text("Approved")'); pg.wait_for_timeout(500)
    ok("Approved" in pg.inner_text("#app .stampmark") and pg.locator('#app label:has-text("Supplier name") input').get_attribute("readonly") is not None, "approved: stamped, and the fields are read-only")
    ok(pg.locator('#app input[aria-label="Expense ledger"]').count() == 0 and "Legal and Professional Charges" in pg.inner_text("#app table.vtbl"), "the ledgers are shown, not editable")
    ok(pg.locator('#app label:has-text("Payment type") select').is_disabled(), "the payment type is locked")
    ok(not errors, "no page errors" + ("" if not errors else ": " + errors[0]))
    br.close()
srv.shutdown()
print("\nall passed" if not fails else "\nFAILED: %d" % len(fails)); raise SystemExit(1 if fails else 0)
