"""python3 run_react_settings.py - Settings (the firm) and Client setup in React: a list of sections on the left, one
section at a time, and the settings in each saved as they are changed. Offline, a made-up client.
Run on the React build: TDSDESK_SITE=../app/dist-test python3 run_react_settings.py"""
import os, threading, functools, http.server
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers")
from playwright.sync_api import sync_playwright
H = functools.partial(http.server.SimpleHTTPRequestHandler, directory=os.environ.get("TDSDESK_SITE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "dist-test"))); H.log_message = lambda *a: None
srv = http.server.ThreadingHTTPServer(("localhost", 8158), H); threading.Thread(target=srv.serve_forever, daemon=True).start()
OUT = os.environ.get("TDSDESK_OUT", "out"); os.makedirs(OUT, exist_ok=True); fails, errors = [], []
def ok(c, w):
    print(("  ok   " if c else "  FAIL ") + w)
    if not c: fails.append(w)
with sync_playwright() as p:
    br = p.chromium.launch(); pg = br.new_page(viewport={"width": 1400, "height": 900}); pg.on("pageerror", lambda e: errors.append(str(e)))
    pg.goto("http://localhost:8158/"); pg.wait_for_timeout(2500); pg.click('button[data-act="useOffline"]'); pg.wait_for_timeout(800)
    head = lambda: pg.inner_text("#app .sethead h2")
    nav = lambda label: pg.click('#app .setnav button:has(span:text-is("%s"))' % label)
    toasts = lambda: pg.evaluate("Array.from(document.querySelectorAll('.toast, #toast')).map(t => t.innerText).join(' | ')")
    # the firm
    pg.evaluate("navHome('rules')"); pg.wait_for_timeout(500)
    ok(head() == "Firm details" and pg.locator("#app .setnav .setgroup-t").count() == 3, "Settings opens on Firm details, sections in three groups")
    pg.fill('#app label:has-text("Firm name") input', "Garg Shekhar & Co (test)"); pg.wait_for_timeout(900)
    ok(pg.evaluate("S.firm.firmName") == "Garg Shekhar & Co (test)" and "Garg Shekhar & Co (test)" in pg.inner_text("#app .setnav"), "the firm's name: kept, and shown in the list")
    for label, text in [("Sign-in and people", "Sign-in and people"), ("Plan and credit", "Plan and credit"), ("Tally Bridge", "Bridge address"), ("Books in the cloud", "Books in the cloud"),
                        ("Sent to Tally", "Everything sent to Tally"), ("TDS rates and limits", "Rates and limits for all clients"), ("Reading bills", "Reading bills"), ("AI help", "AI help")]:
        nav(label); pg.wait_for_timeout(350)
        ok(head() == label and text in pg.inner_text("#app .setbody") and pg.get_attribute('#app .setnav button[aria-current="page"]', "aria-current") == "page", "Settings → " + label)
    ok("Firm name" not in pg.inner_text("#app .setbody"), "the rates page no longer holds the firm's name")
    pg.evaluate("S.settingsTab = null; doAct('goReading')"); pg.wait_for_timeout(300)
    ok(head() == "Reading bills", "the “set up reading” link opens Reading bills")
    pg.screenshot(path=OUT + "/react-settings.png")
    # a client
    pg.evaluate("""() => { const c = newCompany({name: "ZZ Zeta Exports", gstin: ""}); S.companies[c.id] = c; S.data[c.id] = {parties: {}, entries: {}, loaded: true}; c.stats = {}; return openCompany(c.id); }"""); pg.wait_for_timeout(800)
    pg.evaluate("toggleSetup()"); pg.wait_for_timeout(500)
    ok(head() == "Company" and pg.locator("header nav.sbar").count() == 0 and pg.locator("#app .setnav button").count() == 9, "Client setup: nine sections on the left, no row of tabs at the top")
    g = pg.locator('#app label:has-text("GSTIN") input'); g.fill("09aanfg3202d1zr"); g.blur(); pg.wait_for_timeout(500)
    ok(pg.evaluate("CO().gstin") == "09AANFG3202D1ZR" and pg.evaluate("CO().pan") == "AANFG3202D", "GSTIN kept in capitals; the PAN filled in from it")
    pg.fill('#app label:has-text("PAN") input', "AAAAA1111A"); pg.locator('#app label:has-text("PAN") input').blur(); pg.wait_for_timeout(400)
    ok("carries PAN AANFG3202D" in pg.inner_text("body"), "a PAN that does not match the GSTIN: said so")
    pg.fill('#app label:has-text("PAN") input', "AANFG3202D"); pg.locator('#app label:has-text("PAN") input').blur()
    pg.fill('#app label:has-text("Client name") input', "ZZ Zeta Exports Pvt Ltd"); pg.wait_for_timeout(700)
    ok(pg.evaluate("CO().name") == "ZZ Zeta Exports Pvt Ltd", "the client's name")
    nav("Tally"); pg.wait_for_timeout(300)
    ok(head() == "Tally" and "The company in Tally" in pg.inner_text("#app .setbody"), "Tally section")
    pg.select_option('#app label:has-text("Voucher type") select', "Purchase"); pg.wait_for_timeout(300)
    pg.click('#app label:has-text("Optional vouchers") input'); pg.wait_for_timeout(300)
    ok(pg.evaluate("CO().voucherType") == "Purchase" and pg.evaluate("CO().createOptional") is False, "voucher type and Optional vouchers")
    pg.fill('#app label:has-text("Round off") input', "Rounding Off"); pg.wait_for_timeout(700)
    ok(pg.evaluate("CO().roundOff") == "Rounding Off", "a ledger used in every entry")
    nav("TDS"); pg.wait_for_timeout(300)
    pg.click('#app label:has-text("This client has to deduct TDS") input'); pg.wait_for_timeout(300)
    ok(pg.evaluate("CO().mustDeduct") is False and "does not deduct" in pg.inner_text("#app .setnav"), "“has to deduct TDS” off: kept, and the list says so")
    pg.click('#app label:has-text("This client has to deduct TDS") input'); pg.wait_for_timeout(300)
    rid = pg.evaluate("rules().find(r => r.basis !== 'never').id"); lab = pg.evaluate("rules().find(r => r.basis !== 'never').label")
    pg.fill('#app input[aria-label="TDS ledger for %s"]' % lab, "TDS on Contracts"); pg.wait_for_timeout(700)
    ok(pg.evaluate("CO().tdsLedgers['%s']" % rid) == "TDS on Contracts", "a TDS ledger by payment type")
    nav("GST"); pg.wait_for_timeout(1200)
    ok("Blocked credit, section 17(5)" in pg.inner_text("#app .setbody") and "Reverse charge ledgers" in pg.inner_text("#app .setbody"), "GST: registrations, reverse charge ledgers and blocked credit in one place")
    cat = pg.evaluate("BLOCK_CATS[0]")
    pg.select_option('#app select[aria-label="Blocked credit: %s"]' % cat["label"], "allow"); pg.wait_for_timeout(300)
    ok(pg.evaluate("blockRule(CO(), '%s')" % cat["id"]) == "allow", "blocked credit: credit allowed for this client")
    nav("Suppliers"); pg.wait_for_timeout(300)
    ok(head() == "Suppliers" and pg.locator('#app button:has-text("Add supplier")').count() == 1, "Suppliers")
    nav("Bank accounts"); pg.wait_for_timeout(800)
    ok(head() == "Bank accounts", "Bank accounts")
    nav("Bank rules"); pg.wait_for_timeout(500)
    ok(head() == "Bank rules", "Bank rules")
    nav("Closed periods"); pg.wait_for_timeout(300)
    ok("Books closed up to" in pg.inner_text("#app .setbody"), "Closed periods")
    pg.screenshot(path=OUT + "/react-setup.png")
    nav("Remove this client"); pg.wait_for_timeout(300)
    pg.click('#app .setcard button:has-text("Delete client")'); pg.wait_for_timeout(300)
    ok("Click again to delete ZZ Zeta Exports Pvt Ltd" in pg.inner_text("#app .setcard"), "Delete client asks for a second click")
    pg.click('button:has-text("Back to the work")'); pg.wait_for_timeout(400)
    ok(pg.evaluate("S.tab") == "invoices" and pg.evaluate("Object.keys(S.companies).length") == 1, "Back to the work, and the client is still there")
    # the Tally page: the bridge's key and following kept, a Tally chosen and back, a company linked to a client; the cloud's
    # company linked, a computer removed (asked first)
    pg.evaluate("""() => { Bridge.refresh = () => Promise.resolve(); window.startBridgePolling = () => {}; window.bridgeTick = () => {}; Bridge.setCfg({key: '', port: 0, follow: false});
      const cid = S.coId; Bridge.st = {state: 'ok', version: '1.14.3', at: Date.now(), mode: 'auto', tallyUp: true, sessions: [{port: 9000, ok: true, mine: true, companies: [{name: 'ACME LTD'}]}, {port: 9001, ok: true, mine: false, companies: []}], open: []};
      S.view = 'home'; S.homeTab = 'tally'; render(); }"""); pg.wait_for_timeout(400)
    ok("Set up in three steps" in pg.inner_text("#app") and "Tally" in pg.inner_text("#app h2"), "the Tally page, with the three steps")
    k = pg.locator('input[aria-label="Bridge key"]'); k.fill("abc123"); k.press("Tab"); pg.wait_for_timeout(300)
    ok(pg.evaluate("Bridge.cfg().key") == "abc123" and "Check connection" in pg.inner_text("#app"), "the key typed is kept")
    pg.check('label:has-text("Follow the company open in Tally") input'); pg.wait_for_timeout(200)
    ok(pg.evaluate("Bridge.cfg().follow") is True, "following Tally is kept")
    pg.evaluate("render()"); pg.wait_for_timeout(300)
    pg.click('tr:has(td:text-is("Port 9001")) button:text-is("Use this Tally")'); pg.wait_for_timeout(400)
    ok(pg.evaluate("Bridge.cfg().port") == 9001 and "In use" in pg.inner_text("#app table.data"), "one Tally chosen")
    pg.click('button:text-is("Automatic")'); pg.wait_for_timeout(400)
    ok(pg.evaluate("Bridge.cfg().port") == 0, "and back to automatic")
    name = pg.evaluate("CO().name")
    pg.select_option('select[aria-label="Client for ACME LTD"]', pg.evaluate("S.coId")); pg.wait_for_timeout(300)
    ok(pg.evaluate("CO().tallyName") == "ACME LTD", "a Tally company linked to the client")
    pg.evaluate("""() => { window.__tc = []; TCloud.on = () => true; TCloud.refreshPane = async () => {}; TCloud.rpc = async (f, a) => { window.__tc.push([f, a]); return {}; };
      TCloud.pane = {devices: [{id: 'd1', name: 'Office PC', last_seen: null}], companies: [{company: 'BETA', client_id: null}]}; S.homeTab = 'rules'; S.settingsTab = 'tcloud'; render(); }"""); pg.wait_for_timeout(400)
    pg.select_option('select[aria-label="Client for BETA"]', pg.evaluate("S.coId")); pg.wait_for_timeout(400)
    ok(pg.evaluate("window.__tc[0]") == ["tally_company_link", {"p_company": "BETA", "p_client": pg.evaluate("S.coId")}], "the cloud's Tally company linked to a client")
    pg.click('button:text-is("Remove")'); pg.wait_for_timeout(300)
    ok(pg.locator("#confirmBox .cbx").is_visible(), "removing a computer asks first")
    pg.click('#confirmBox button[data-cbx="yes"]'); pg.wait_for_timeout(400)
    ok(pg.evaluate("window.__tc[1]") == ["tally_device_revoke", {"p_id": "d1"}], "and removes it")
    ok(not errors, "no page errors" + ("" if not errors else ": " + errors[0]))
    br.close()
srv.shutdown()
print("\nall passed" if not fails else "\nFAILED: %d" % len(fails)); raise SystemExit(1 if fails else 0)
