"""python3 run_mis2_ui.py - MIS phase 2 tabs in a browser."""
import json, os, sys, threading, functools, http.server
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers")
from playwright.sync_api import sync_playwright
H = functools.partial(http.server.SimpleHTTPRequestHandler, directory=os.environ.get("TDSDESK_SITE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "site-test"))); H.log_message = lambda *a: None
srv = http.server.ThreadingHTTPServer(("localhost", 8131), H); threading.Thread(target=srv.serve_forever, daemon=True).start()
OUT = os.environ.get("TDSDESK_OUT", os.path.join(os.path.dirname(os.path.abspath(__file__)), "out"))
books = json.load(open(os.environ.get("TDSDESK_CACHE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "books-cache.json"))))
fails, errors = [], []
def ok(c, w):
    print(("  ok   " if c else "  FAIL ") + w)
    if not c: fails.append(w)
with sync_playwright() as p:
    br = p.chromium.launch(); ctx = br.new_context(viewport={"width": 1400, "height": 1000}); pg = ctx.new_page()
    pg.on("pageerror", lambda e: errors.append(str(e)))
    pg.goto("http://localhost:8131/"); pg.wait_for_timeout(2500)
    pg.click('button[data-act="useOffline"]'); pg.wait_for_timeout(1500)
    pg.evaluate("""(bk) => { const c = newCompany({name: "ZZ TEST (VMS books)", gstin: "07AADCV3366N1ZU"}); S.companies[c.id] = c; S.coId = c.id; S.view = "company"; S.tab = "books"; S.loadingCo = false;
      S.books = Object.assign({loading: false, challans: [], alloc: {}}, bk, {cid: c.id, misCfg: {freq: "off"}, auditCfg: {freq: "off"}}); S.books.map = Books.mapLedgers(bk.vouchers, {}); window.__bk = S.books; S.booksTab = "import"; render(); }""", books)
    pg.wait_for_timeout(1200); pg.evaluate("S.books = window.__bk; render();"); pg.wait_for_timeout(600)
    pg.set_input_files("#mastersIn", os.path.join(os.environ.get("TDSDESK_DATA", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")), "Master.xml")); pg.wait_for_timeout(12000)
    pg.evaluate("S.booksTab = 'mis'; render();"); pg.wait_for_timeout(400)
    pg.click('button[data-misquick="lastyear"]'); pg.click('button[data-act="misRun"]'); pg.wait_for_timeout(4000)
    pg.click('button[data-mistab="cash"]'); pg.wait_for_timeout(500)
    t = pg.inner_text("#app")
    ok("From operations" in t and "Net change in cash and bank" in t and "The next 13 weeks" in t, "cash flow and 13 weeks")
    pg.locator("button[data-miscf]").first.click(); pg.wait_for_timeout(400)
    ok(pg.locator("#app td.note").count() > 0, "a cash flow line opens to its ledgers")
    pg.click('button[data-misweek="0"]'); pg.wait_for_timeout(400)
    ok("Why this date" in pg.inner_text("#app").title() or "usually paid in" in pg.inner_text("#app"), "a week opens to its items and why")
    pg.screenshot(path=OUT + "/mis-cash.png", full_page=False)
    pg.click('button[data-mistab="ratios"]'); pg.wait_for_timeout(400)
    ok("Gross margin" in pg.inner_text("#app") and "Margins month by month" in pg.inner_text("#app"), "ratios")
    pg.click('button[data-mistab="regs"]'); pg.wait_for_timeout(400)
    ok("07AADCV3366N1ZU" in pg.inner_text("#app") and "09AADCV3366N1ZQ" in pg.inner_text("#app"), "both registrations")
    pg.click('button[data-mistab="cc"]'); pg.wait_for_timeout(500)
    t = pg.inner_text("#app")
    ok("HP SALE" in t and "Income allocated" in t, "profit by cost centre")
    pg.fill("#misq", "PMI"); pg.wait_for_timeout(700)
    ok(pg.locator("#misCc > tbody > tr").count() >= 1 and "HP SALE" not in pg.inner_text("#misCc"), "cost centres filter")
    pg.locator("button[data-miscc]").first.click(); pg.wait_for_timeout(400)
    ok(pg.locator("#misCc table").count() == 1, "a cost centre opens to its ledgers")
    pg.screenshot(path=OUT + "/mis-cc.png", full_page=False)
    pg.click('button[data-mistab="budget"]'); pg.wait_for_timeout(400)
    ok("No budget for this year yet" in pg.inner_text("#app"), "budget: none yet")
    pg.click('button[data-act="misBudFill"]'); pg.wait_for_timeout(600)
    ok("budget for the period" in pg.inner_text("#app").lower(), "filled from this year's actual plus 10%")
    pg.fill('input[data-misbud="rev|202504"]', "10000000"); pg.press('input[data-misbud="rev|202504"]', "Tab"); pg.wait_for_timeout(500)
    ok(pg.evaluate("S.books.budget['2025'].rev['202504']") == 10000000, "a month of the budget changed by hand")
    with ctx.expect_page() as pop:
        pg.click('button[data-act="misPack"]')
    rp = pop.value; rp.wait_for_timeout(800); rt = rp.inner_text("body")
    ok("Cash flow" in rt and "The next 13 weeks" in rt and "Budget against actual" in rt and "Cost centres, largest 15" in rt, "the pack carries phase 2")
    rp.pdf(path=OUT + "/mis-pack2.pdf"); rp.close()
    bad = pg.evaluate("""() => { const bad = []; ['summary', 'pl', 'recv', 'pay', 'sales', 'purch', 'cash', 'ratios', 'regs', 'cc', 'budget', 'comp'].forEach(tb => { S.misTab = tb; try { render(); } catch (e) { bad.push(tb + ': ' + e.message); } }); return bad; }""")
    ok(not bad, "every tab renders" + ("" if not bad else ": " + "; ".join(bad)))
    br.close()
errs = [e for e in errors if "supabase" not in e and "Failed to load" not in e]
ok(not errs, "no page errors" + ("" if not errs else ": " + " | ".join(errs[:4])))
print("\n" + ("%d FAILED" % len(fails) if fails else "all passed")); sys.exit(1 if fails else 0)
