// The screens already in React, by the name the old screens use to place them (<div data-react="Name" data-…>).
import GstApiCard from "./GstApiCard.jsx";
import GstApiAll from "./GstApiAll.jsx";
import FiledCompare from "./gst/FiledCompare.jsx";
import VendorRecon from "./VendorRecon.jsx";
import Today from "./Today.jsx";
import InboxAll from "./InboxAll.jsx";
import Clients from "./Clients.jsx";
import Collect from "./Collect.jsx";
import Invoices from "./Invoices.jsx";
import BillDetail from "./Bill.jsx";
import { ReviewTable, ActionBar, Drawer } from "./Review.jsx";
import Parties from "./Parties.jsx";
import { PostStep, Export } from "./Post.jsx";
import { DoneStep, PostLog } from "./Done.jsx";
import Bank, { BankBar } from "./Bank.jsx";
import { FirmSettings, ClientSetup } from "./Settings.jsx";
import Sales, { SalesBar } from "./Sales.jsx";
import Txn from "./Txn.jsx";
import Dash from "./Dash.jsx";
import Books from "./Books.jsx";
import Gst from "./Gst.jsx";
import TallyHome from "./Tally.jsx";
import Help from "./Help.jsx";
import DocqPanel from "../parts/Docq.jsx";
import Unsorted from "../parts/Unsorted.jsx";
import UploadBlock from "../parts/UploadBlock.jsx";
import { Jobs, ReadingCheck, UploadOptions, Working } from "../parts/Reading.jsx";

export default { GstApiCard, GstApiAll, FiledCompare, VendorRecon, Today, InboxAll, Clients, Collect, Invoices, BillDetail, ReviewTable, ActionBar, Drawer, Parties, PostStep, Export, DoneStep, PostLog, Bank, BankBar, FirmSettings, ClientSetup, Sales, SalesBar, Txn, Dash, Books, Gst, TallyHome, Help, DocqPanel, Unsorted, UploadBlock, Jobs, ReadingCheck, UploadOptions, Working };
